services:
  - type: web
    name: medicpro
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: medicpro-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: medicpro-db
    databaseName: medicpro
    plan: starter